### ISSUE TITLE
SpongePls Error

### ISSUE THREAD

**Issue by ice4ed** [SilverCory/SpongePls#1]
Okay so I am setting up my server to run 2 gamemodes a spigot server (Towny) and a Forge Sponge server (RPG) but I am running into issues connecting them with Bungee, The spigot server is the default server it has the hub and our Towny world then we have a RPG server that has forge mods and sponge plugins in it currently runs Forge 1.8.9 version 1763 and Sponge 1.8.9 version 1763

I added SpongePls to our Bungeecord plugins and I assume in allowed server I was supposed to put the name of the servers in the config so I put in both of them and after restarting I was unable to connect to the server with a Forge client as I would get the message "If you wish to use IPForwarding you must enable it in you BungeeCord config as well!"

**Comment by Darktilldawn** [comment]
Well what you need to do, is turn your servers to offline mode, and go into your spigot/sponge file and turn IP Forwarding on, You must Also do this in your bungeecord settings.

**Comment by ice4ed** [comment]
I double checked my settings just in case but the servers are in offline mode and bungeecord was set to true for both in the spigot.yml and spogne config and BungeeCord has ip forwarding set to true. I was able to BungeeCord my spigot server before I added SpongePls but now that Forge is in the equation I am unable to use Forge clients with SpongePls it does not allow me to connect like it should for some reason.

**Comment by Darktilldawn** [comment]
Try this version of it
https://www.dropbox.com/s/twi8i8pzalx7mpo/SpongePls.jar?dl=0

**Comment by ice4ed** [comment]
Same result with this version

**Comment by Darktilldawn** [comment]
Is that Forge server running sponge?

**Comment by ice4ed** [comment]
Yes

**Comment by Darktilldawn** [comment]
Alright send me the sponge properties file, the bungee one, and the spongepls one and maybe I can find the mistake, use pastebin

**Comment by ice4ed** [comment]
SpongePls config: http://pastebin.com/8tA60Uf9
Sponge Properties: http://pastebin.com/p0Nds6aG
Forge Server Properties: http://pastebin.com/ipbk8mcM
BungeeCord Server Properties: http://pastebin.com/Us1Xh895

**Comment by Darktilldawn** [comment]
bungeecord module is set to false inside the Sponge Properties, it must be true

**Comment by ice4ed** [comment]
Still same error, I believe the problem resides in SpongePls not connecting my forge client to the Spigot server that is where I go first and my console says it tries to use the Forge connector but says I disconnect for the same error almost as if it isn't using the proxy like if I tried to direct connect to the server.

**Comment by ice4ed** [comment]
If you need any more logs or files that might help diagnose let me know, I am also available by skype if that would help any at all

**Comment by SilverCory** [comment]
Sponge, spigot and bungeecord versions please.

**Comment by ice4ed** [comment]
Spigot version: CraftBukkit version git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

SpongeForge: 1.8.9-1808-4.1.0-BETA-1286

BungeeCord version: BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:7d2c2ab:1119 by md_5

**Comment by SilverCory** [comment]
From what I can see there is no error here, you need to set up the servers properly.

Ensure all the server are in offline mode and have bungeecord ipforwarding enabled, and on the proxy ensure ipforwarding also is enabled.

**Comment by ice4ed** [comment]
The servers are in offline mode and ip forwarding is enabled on the bungeecord and proxy, like i said earlier I was able to use Bungee perfectly until I tried to use SpongePls with it and it did not use the Forge connector properly for some reason.

**Comment by SilverCory** [comment]
Remove it, if it defo works then it's my issue.

**Comment by SilverCory** [comment]
Closing because I presume you fixed it..
