### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by SequaciousGAMES** [SilverCory/SpongePls#10]
Simply, plugin doesn't load on Bungee
https://pastebin.com/JYtRvSMF
Bungee 1229
Latest build of SpongePls as of this message

**Comment by SilverCory** [comment]
Invalid or corrupt jar, re-download properly..

**Comment by SequaciousGAMES** [comment]
I download it using the Sponge website and your continuous integration server, idk how else to get it

**Comment by SilverCory** [comment]
It's probably how you're downloading it..?
