### ISSUE TITLE
Can't download?

### ISSUE THREAD

**Issue by SenpaiDerp** [SilverCory/SpongePls#12]
I've tried here and on the spigot page to download this, but no source allows it through.  I've also had someone else try to download the source to compile it and that didn't work either.  Any idea whats up?

**Comment by EmanYm** [comment]
Try the Jenkins repo
http://ci.ac3-servers.eu/job/SpongePls/

**Comment by SilverCory** [comment]
Thanks, sorry the ci server ran out of disk space, all finished re partitioning so it shouldn't be an issue.
