### ISSUE TITLE
No matter what I do, I cannot seem to get this to work right.

### ISSUE THREAD

**Issue by doglover129** [SilverCory/SpongePls#2]
I have followed the setup, I think, exactly. I am currently using a 1.8.8 spigot server as my 'hub' and trying to use Spongepls to allow users to connect to a 1.8.9 forge server, that has spigot in the mods folder, and I cannot for the life of me get it to work. Every time bungee just says "connected" and immediately says "disconnected." We get no where beyond that. No notification of it even trying to send me onto the server. I'll provide any logs you need to help me figure this one out. Thanks.

**Comment by SilverCory** [comment]
I've not kept up with everything, should still work unless sponge removed the part of the code required.

**Comment by Snipershotmaster** [comment]
I was going to make a new post about this issue but it seems you have already done so. I receive the exact problem. Every time a player would join my forge server (No other mods except sponge. Testing this plugin.), the log would say "[Spongepls]  for the target 'Forge'" and soon after that, it would say the player has connected and immediately disconnected. My Sponge configuration only has "ip-forwarding" on true and "bungeecord" on true. This is a head scratcher for me

**Comment by SilverCory** [comment]
@Snipershotmaster still going to stick to my last comment, there's no reason for this to stop working unless sponge changed some stuff?
