### ISSUE TITLE
Blocks non Sponge servers

### ISSUE THREAD

**Issue by GershonR** [SilverCory/SpongePls#3]
When I add this to Bungee, anytime I connect to a server that's on 1.10 Spigot it kicks me to enable IP-Forwarding, I checked the config and allowed the server exactly as spelled on the Bungee config yet it still kicks.

So just to clarify when I add this I cannot connect to any servers but when I remove it I can connect to them fine.

**Comment by Snipershotmaster** [comment]
Remove the line "  - '.*'" this whitelists all servers.

**Comment by SilverCory** [comment]
As the above post says, this is misconfiguration.
