### ISSUE TITLE
Cannot Connect to Modded Forge Server

### ISSUE THREAD

**Issue by Tommsy64** [SilverCory/SpongePls#9]
I cannot connect to a modded Sponge server using SpongePls.

##### How to Reproduce

1. Run a Bungee proxy with SpongePls installed
2. Run a forge 1.10.2 server with Sponge installed.
3. Enable ip-forwarding, bungee module, set online mode to false.
4. At this point, you can connect to Sponge server through Bungee fine.
5. Add any client+server side mod. (Like [Snad](https://minecraft.curseforge.com/projects/snad))
6. Try connecting to Sponge server through Bungee:
7. Get error message 😢 
![image](https://cloud.githubusercontent.com/assets/3900951/24784816/24ab8ea2-1b23-11e7-91de-df816aa9e446.png)

Does this have something to do with extra forge data in the login connection not properly being read on the server?

**Comment by SilverCory** [comment]
Not a clue tbh, try DualSphere's thing..>?

**Comment by Tommsy64** [comment]
Dualspiral's [SpongeIPForwarding](https://github.com/dualspiral/SpongeIPForwarding) works perfectly! Didn't realize that existed.
